# Build Job to be used between main and pages

name: Build

on:
  workflow_call:

jobs:
  build:
    # Match Development Operating System
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        # Match Development Node Version
        node-version: '16.x'

    - name: Clean Install
      run: npm ci

    # Check Environment
    - name: Check
      env:
        BRANCH_NAME: ${{ github.ref }}
      run: npm run check-environment --if-present

    # 'npm run build' broken into separate steps
    - name: clean
      run: npm run clean

    - name: style
      run: npm run style-check

    - name: compile
      run: npm run compile