# Main workflow to keep branches clean

name: Main

on:
  # main branch CI
  push:
    branches:
      - 'main'

  # Run on pull request
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

