# Main workflow to keep branches clean

name: Main
run-name: ${{ github.workflow }} for ${{ github.ref }}

on:
  # main branch CI
  push:
    branches:
      - 'main'

  # Run on pull request
  pull_request:
    types: [ opened, synchronize ]

# Cancel current workflow if there is already one running
# concurrency: 
#   group: ${{ github.workflow }} ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/templates/build.yml

