# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main

on:
  # main branch CI
  push:
    branches: [ main ]

  # Manual
  workflow_dispatch:

jobs:
  build:
    # Match Development Operating System
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        # Match Development Node Version
        node-version: '16.x'

    - name: Clean Install
      run: npm ci

    # Check Environment
    - name: Check
      env:
        BRANCH_NAME: ${{ github.ref }}
      run: npm run check-environment --if-present

    # 'npm run build' broken into separate steps
    - name: clean
      run: npm run clean

    - name: style
      run: npm run style-check

    - name: compile
      run: npm run compile

    - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/upload-pages-artifact
        path: dist/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

