name: Playwright Tests
on:
  push:
    branches: [ main, wandyezj/test ]
  pull_request:
    branches: [ main, wandyezj/test ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci

    # needs compiled file to test with
    - name: compile
      run: npm run compile

    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps


    # only install browsers that are tested
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps chromium
      
    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30

    - name: Install Playwright Browsers
      run: npm run playwright-install

    - name: Run Playwright tests
      run: npm run playwright-test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
